name: deploy

on:
  push:
    branches: 
      - 'master'
      - 'release'
  release:
    types:
      - published

jobs:
  staging:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'master'
    environment: 
      name: staging
      url: https://dashboard-test.btfs.io
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build dashboard
        run: npm install && npm run build

      - name: Upload dashboard build
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "build"
          target: "~"

      - name: Publish dashboard build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export BTFS_PATH=${{ secrets.BTFS_PATH }}
            cd ${{ secrets.BTFS_BIN_PATH }}
            ./btfs name publish /btfs/$(./btfs add -r ~/build | tail -1 | awk '{print $2}')
            rm -rf ~/build